/**
 * The story behind the capital — where the name came from, or why the seat is
 * where it is. Keyed by ISO 3166-1 alpha-3, so a country can be renamed on the
 * map without losing its line.
 *
 * Every entry is a plain, checkable claim. A capital with no entry gets the
 * measured line from `factLine` instead: an empty space is better than an
 * invented one.
 */
export const CAPITAL_STORIES: Record<string, string> = {
  ARM: "Yerevan dates itself from the Urartian fortress of Erebuni, founded in 782 BC — twenty-nine years older than Rome.",
  EGY: "Al-Qāhira, “the victorious”, founded by the Fatimids in 969 beside the older cities of Fustat and Memphis.",
  BRA: "Built from nothing on an empty plateau and inaugurated in 1960, to pull the country inland from its coast.",
  JPN: "Edo became Tōkyō, “eastern capital”, in 1868, when the emperor left Kyoto and never went back.",
  FRA: "Named for the Parisii, the Gaulish tribe that held the island in the Seine the city still grew out of.",
  GBR: "Londinium was a Roman trading town on the tidal head of the Thames, founded around AD 47.",
  USA: "Placed on the Potomac by the compromise of 1790, on ground ceded by Maryland and Virginia, and surveyed by Andrew Ellicott and Benjamin Banneker.",
  CAN: "A lumber town picked by Queen Victoria in 1857 precisely because it was neither Montreal nor Toronto — and sat safely back from the border.",
  AUS: "A compromise between Sydney and Melbourne, laid out to Walter Burley Griffin and Marion Mahony Griffin's plan from 1913.",
  NZL: "The seat moved from Auckland in 1865 because Wellington sat on the strait, within reach of both islands.",
  RUS: "First written down in 1147 as a minor outpost; the Kremlin's walls have been wood, white limestone and finally brick.",
  CHN: "Beijing means “northern capital”. The Ming moved the court there from Nanjing in 1421 and built the Forbidden City to receive it.",
  IND: "New Delhi was Lutyens' city, begun after the capital left Calcutta in 1911 and inaugurated in 1931 — the eighth or so Delhi on the same plain.",
  PAK: "Built in the 1960s beside Rawalpindi to take the capital out of Karachi, and named simply “city of Islam”.",
  NGA: "Purpose-built in the centre of the country and made capital in 1991, to give the federation a seat that belonged to no region.",
  KEN: "From the Maasai enkare nyorobi, “cool water” — a railway depot pitched at a swamp in 1899 because the locomotives needed to refill there.",
  ETH: "Addis Ababa means “new flower”, named by Empress Taytu when she and Menelik II founded it at the hot springs in 1886.",
  ITA: "Rome counts its founding from 753 BC on the Palatine, and has been continuously inhabited ever since.",
  GRC: "Athens took its name from Athena, whose olive tree beat Poseidon's salt spring in the contest for the city.",
  ESP: "Madrid grew from Mayrit, a 9th-century Andalusi fortress on the Manzanares, and became capital in 1561 for sitting in the middle of Iberia.",
  PRT: "Roman Olisipo, and one of the oldest cities in western Europe; the downtown grid is Pombal's, rebuilt after the 1755 earthquake.",
  DEU: "Two trading towns, Berlin and Cölln, facing each other across the Spree in the 13th century.",
  AUT: "Vindobona was a Roman legionary camp on the Danube; the old city still follows its outline.",
  NLD: "A dam on the river Amstel, thrown up in the 13th century — the name is the engineering.",
  BEL: "From broekzele, “settlement in the marsh”, on the Senne.",
  CHE: "Bern's founding legend has Berchtold V naming the city for the first animal he killed on the hunt: a bear. The bear is still on the arms.",
  SWE: "Stockholm was founded in 1252 at the lock between Lake Mälaren and the Baltic — whoever held the islands held the trade.",
  NOR: "Burned in 1624 and rebuilt as Christiania by the Danish king; the city took back the name Oslo in 1925.",
  DNK: "København is køpmannæhafn, “merchants' harbour”, fortified by Bishop Absalon in 1167.",
  FIN: "The capital moved from Turku in 1812 to sit further from Sweden and nearer St Petersburg; Engel built the neoclassical centre to match.",
  ISL: "Reykjavík means “smoky bay”, for the steam Ingólfr Arnarson saw rising from the hot springs when he landed.",
  IRL: "Dublin is Dubh Linn, the “black pool” on the Poddle where the Vikings moored.",
  POL: "Warsaw's old town is a reconstruction: rebuilt after 1945 from drawings, photographs and Canaletto's cityscapes.",
  CZE: "Prague Castle has been the seat above the Vltava since the 9th century, and is the largest ancient castle complex in the world.",
  HUN: "Buda and Óbuda on the hills, Pest on the flat — one city only since 1873.",
  ROU: "Bucharest's legend gives it a shepherd called Bucur; the first record is Vlad III's, in 1459.",
  BGR: "Sofia is named after its 6th-century church of Hagia Sophia, not the other way round.",
  SRB: "Beograd, “white city”, on the ridge where the Sava meets the Danube — fought over more than almost anywhere in Europe.",
  UKR: "Kyiv takes its name from Kyi, eldest of the siblings who legend says founded it above the Dnipro.",
  TUR: "Atatürk moved the capital inland to Ankara in 1923, away from the sea and the Ottoman city.",
  IRN: "A village under the Alborz until the Qajars made it their capital in 1786.",
  IRQ: "Baghdad began in 762 as al-Mansur's Round City, laid out as a perfect circle on the Tigris.",
  SAU: "Riyadh is ar-riyāḍ, “the gardens” — the oasis meadows at the wadi.",
  ARE: "Abu Dhabi means “father of the gazelle”, from the animal that led the hunting party to fresh water on the island.",
  KWT: "Kuwait is a diminutive of kut, a fort — the small fort by the bay.",
  JOR: "Roman Philadelphia, and before that Rabbath Ammon of the Ammonites; the name Amman kept the older one.",
  LBN: "Beirut's name comes from the wells, be'erot, that made the site liveable.",
  SYR: "Damascus has been inhabited without a break for some four thousand years, on the Barada that waters the Ghouta.",
  GEO: "Tbilisi is “warm place”. King Vakhtang's hawk, the legend goes, fell into a hot spring and the city was built there.",
  AZE: "Baku sits on a peninsula in the Caspian whose winds gave it the name, and whose oil seeps were burning long before drills.",
  KAZ: "The seat moved from Almaty onto the open steppe in 1997; the city has been renamed three times since.",
  UZB: "Tashkent is “stone city” in Turkic, a Silk Road staging post rebuilt after the 1966 earthquake.",
  MNG: "Ulaanbaatar, “red hero”, settled in 1924 after a century and a half of moving; the coldest capital on earth.",
  KOR: "Seoul is not a loan word — it simply means “capital” in Korean.",
  PRK: "Pyongyang means “flat land”, on the Taedong; it claims to be the oldest city on the peninsula.",
  VNM: "Hanoi is “inside the river”, held between the Red River and its dikes; before that it was Thăng Long, “ascending dragon”.",
  THA: "Bangkok's ceremonial name runs to 168 letters and holds the record for the longest place name in the world. Thais call it Krung Thep.",
  IDN: "Batavia took back the name Jakarta in 1942. It is sinking, and the seat of government is moving to Nusantara on Borneo.",
  MYS: "Kuala Lumpur is “muddy confluence”, the point where the Klang and the Gombak meet — a tin prospectors' landing.",
  SGP: "Singapura, “lion city”, from a sighting that was more likely a tiger.",
  PHL: "Manila comes from may nilad, “where the nilad grows”, a flowering shrub of the bay's mangroves.",
  NPL: "Kathmandu is named for Kasthamandap, a pavilion said to have been built from the timber of a single tree.",
  LKA: "Sri Jayawardenepura Kotte holds the parliament; Colombo, the old harbour, still holds almost everything else.",
  MEX: "Mexico City stands on the drained bed of Lake Texcoco, over the Mexica capital Tenochtitlan — and is still sinking into it.",
  ARG: "Buenos Aires was founded twice, in 1536 and again in 1580; the name is a sailors' shrine, Santa María del Buen Ayre.",
  PER: "Pizarro founded Lima in 1535 and called it the City of Kings; the name is the Rímac river, heard in Spanish.",
  CHL: "Santiago was laid out by Pedro de Valdivia in 1541 between the Mapocho and the hill of Huelén.",
  COL: "Bogotá takes its name from Bacatá, the Muisca seat on the same high savanna.",
  ECU: "Quito sits almost exactly on the equator at 2,850 m, on the site the Inca ran as their northern capital.",
  BOL: "La Paz is the highest seat of government in the world, in a canyon below El Alto — though Sucre remains the constitutional capital.",
  CUB: "Havana's harbour was the mustering point where the Spanish treasure fleets gathered before crossing the Atlantic together.",
  ZAF: "Three capitals: Pretoria executive, Cape Town legislative, Bloemfontein judicial — the price of the 1910 union.",
  COD: "Kinshasa and Brazzaville face each other across the Congo: the closest pair of capital cities in the world.",
  COG: "Brazzaville is named for Pierre Savorgnan de Brazza, and looks across the river at Kinshasa.",
  TZA: "Dodoma was made capital in 1974 for being central, but Dar es Salaam — “harbour of peace” — kept the ministries for decades.",
  CIV: "Yamoussoukro was Houphouët-Boigny's birthplace, made capital in 1983; Abidjan still runs the country's business.",
  MMR: "Naypyidaw was built in secret and the government moved there overnight in 2005, from Yangon.",
  GHA: "Accra grew from Ga settlements around three European forts; the name comes from nkran, the ants.",
  SEN: "Dakar sits on the Cap-Vert peninsula, the westernmost point of continental Africa.",
  MDG: "Antananarivo is “the city of the thousand”, for the soldiers posted to hold its hill.",
  UGA: "Kampala was built on hills — the name comes from impala, the antelope the kabaka hunted there.",
  ZWE: "Salisbury was renamed Harare in 1982, after the Shona chief Neharawa.",
  MAR: "Rabat began as a ribat, a fortified monastery, at the mouth of the Bou Regreg.",
  DZA: "Algiers is al-Jazā'ir, “the islands”, for the islets once off its shore.",
  TUN: "Tunis took over from Carthage, which the Romans levelled a few kilometres away.",
  ISR: "The seat of government sits in Jerusalem; most countries keep their embassies in Tel Aviv, and the city's status is disputed.",
  PSE: "Ramallah holds the Palestinian Authority's offices; Palestinians claim Jerusalem as capital, and the status is disputed.",
};

/** The curated line, or nothing — never a filler sentence. */
export const storyFor = (iso: string | undefined): string | null =>
  (iso && CAPITAL_STORIES[iso]) || null;
